import { ColumnDef } from "@tanstack/react-table";
import { Search, Archive, Eye } from "lucide-react";
import { Link } from "react-router-dom";
import { DataTable } from "../../components/ui/DataTable";
import { LoadingShell } from "../../components/ui/LoadingShell";
import { useTimetables } from "../../hooks/useResources";
import type { RawTimetable } from "../../utils/timetable";

export const TimetablesPage = () => {
  const query = useTimetables();
  const data = (query.data ?? []) as RawTimetable[];
  // "timetable_id":1,"section":5,"section_name":"A","term":2,"term_label":"2026-2027 Even","version_number":1,"status":"GENERATED","generated_at":"2026-06-01T20:06:23.165654+05:30","generated_by":3,"generated_by_email":"magantinavadeep@gmail.com","published_at":null}
  const columns: ColumnDef<RawTimetable>[] = [
    { header: "ID", accessorKey: "timetable_id" },
    { header: "Section", accessorKey: "section_name" },
    { header: "Term", accessorKey: "term_label" },
    { header: "Version", accessorKey: "version_number" },
    { header: "Status", accessorKey: "status" },
    { header: "Generated At", accessorKey: "generated_at" },
    { header: "Generated By", accessorKey: "generated_by_email" },
    {
      header: "Actions",
      accessorKey: "actions",
      cell: ({ row }) => (
        <div className="flex items-center gap-2">
          <Link
            to={`/timetables/list/${row.original.timetable_id}`}
            className="rounded-2xl border border-slate-700 bg-slate-950 px-3 py-2 text-slate-300 hover:bg-slate-900"
            title="View timetable"
          >
            <Eye size={16} />
          </Link>
          <button className="rounded-2xl border border-slate-700 bg-slate-950 px-3 py-2 text-brand-400 hover:bg-slate-900">
            Publish
          </button>
          <button className="rounded-2xl border border-slate-700 bg-slate-950 px-3 py-2 text-slate-400 hover:bg-slate-900">
            <Archive size={16} />
          </button>
        </div>
      ),
    },
  ];

  if (query.isLoading) return <LoadingShell />;

  return (
    <div className="space-y-6">
      <div className="rounded-3xl border border-slate-800 bg-slate-900 p-6 shadow-soft">
        <div className="mb-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.24em] text-slate-500">
              Timetables
            </p>
            <h2 className="text-3xl font-semibold text-white">Timetables</h2>
          </div>
          <div className="relative">
            <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" />
            <input
              type="search"
              placeholder="Search timetable versions"
              className="w-full rounded-3xl border border-slate-800 bg-slate-950 py-3 pl-12 pr-4 text-slate-100 outline-none focus:border-brand-500"
            />
          </div>
        </div>
        <DataTable
          columns={columns}
          data={data}
          emptyText="No timetables available."
        />
      </div>
    </div>
  );
};
